### ISSUE TITLE
function createSwap() {...}

### ISSUE THREAD

**Issue by tim0n3** [Opennetworks-com/ed-iot#1]
# Create the swap file based on amount of physical memory on machine (Maximum size of swap is 4GB)
function createSwap() {
   local swapmem=$(($(getPhysicalMemory) * 2))

   # Anything over 100MB in swap is probably unnecessary as a RAM fallback for Pi's
   if [ ${swapmem} -gt 4 ]; then
        swapmem=100
   fi

   sudo fallocate -l "${swapmem}M" /swapfile
   sudo chmod 600 /swapfile
   sudo mkswap /swapfile
   sudo swapon /swapfile
}

Function should set swap to 100M not in GB as we shouldn't be swapping to the TF card anyway.

**Comment by chesterlprocter** [comment]
Removed in Final Code.
