### ISSUE TITLE
ubuntu core is entirely snap based

### ISSUE THREAD

**Issue by tim0n3** [Opennetworks-com/ed-iot#3]
Can't do much in the way of configuring ubuntu core as it's entirely based on snaps (snapd) . everything including the base system runs within a snap container. This means the distro would be better suited for containerization instead of PaaS/SaaS activities like we require.

Please, update the readme accordingly

**Comment by chesterlprocter** [comment]
Ubuntu Core and the Snaps build is focused around Dev environments. The End result of the IoT service offering is to ensure IoT devices have robust Security to serve a single purpose. 

Ubuntu core is the Industry Standard for IoT at the moment as it has core features we discussed with regards to self management and healing. 

I've recommended the Core version versus LTS (Long Term Support) as the Dependencies and Libraries loaded by default are extensively aimed at a fully interactable out-of-the-box Ubuntu where IoT devices need to operate more on the module code aimed at Data Ingestion.

However, you are correct with regards to snap, the containerized environment did mean that our loadout parameters needed to be adjusted for snap deployment .

At the Moment: I am experiencing Snapcraft issues with Multipassing where Multipass is only supported in  channels:
       candidate  snap install --candidate multipass
       beta       snap install --beta multipass
       edge       snap install --edge multipass
       
This Configuration I'm trying to automate has a few steps that require configuration before automation can apply.

On other IoT builds we've done; we've used Base Ubuntu are stripped out wasted dependencies / libraries not needed. But this Industry way is are core install to only install needed Dependencies. Its Light weight and replaces the old Ubuntu Lite (Lubuntu) which used to be the old industry standard.

**Comment by tim0n3** [comment]
Perhaps we can discuss in a seperate meeting, however lubuntu is ubuntu with lxde/lxqt desktop environments slapped on (amongst other distro-specific tools) instead of the unity desktop environment. we're using the headless lts (no-gui) build of ubuntu

lubuntu home page: https://lubuntu.net/#:~:text=It%20is%20a%20Linux%20system%2C%20that%20uses%20the%20minimal%20desktop%20LXDE/LXQT
