### ISSUE TITLE
_modem_service_install() {} needs to be adapted for ubuntu

### ISSUE THREAD

**Issue by tim0n3** [Opennetworks-com/ed-iot#5]
This is my function from my autopai git repo https://github.com/tim0n3/AutoPai and it needs to be adapted for ubuntu either by modifying the case statement or by checking the OS in the /etc/os-releases file and the correct config should apply as this doesn't use the correct service files anymore due to the rewrite of the program from v1.9 to v1.10-rc1

_modem_service_install() {
	read -n1 -p "Install modem & watchdog service? (y/n):" serviceinstall
	case ${serviceinstall:0:1} in
	y|Y )
		echo "--------------------------------------"
		echo "--   SystemV service install        --"
		echo "--------------------------------------"
		cp /home/pi/app/energydrive.service /etc/systemd/system/energydrive.service ;
		cp /home/pi/app/watchdog.service /etc/systemd/system/watchdog.service ;
		systemctl enable energydrive.service ;
		systemctl stop energydrive.service ;
		systemctl enable watchdog.service ;
		systemctl stop watchdog.service ;
##ubuntu
		#cp /home/ubuntu/app/energydrive.service /etc/systemd/system/energydrive.service ;
		#cp /home/ubuntu/app/watchdog.service /etc/systemd/system/watchdog.service ;
		#systemctl enable energydrive.service ;
		#systemctl stop energydrive.service ;
		#systemctl enable watchdog.service ;
		#systemctl stop watchdog.service ;

	;;
	n|N )
		echo "You've opted to install the services later"
	;;
	esac
}

**Comment by chesterlprocter** [comment]
Corrected, as I moved away from a Py Script and Rather focused on your Bash loadouts per the configurations you requested. I am Directing the loadout to build out based on your git repo.

In this test Repo I simply cloned your Bash commands at the time to test loadout compatibility.

The final Build where you will have for Ownership over will be based on your initial written loadout , but will be configured to loadout to the new configuration standards.
