### ISSUE TITLE
_create_crontabs() {} where's the internet script that has the functions to check internet?

### ISSUE THREAD

**Issue by tim0n3** [Opennetworks-com/ed-iot#6]
check-internet.sh doesn't exist in this repo.

_create_crontabs() {
	echo "--------------------------------------"
	echo "--        Creating crontabs:        --"
	echo "--------------------------------------"
	cat <<EOF | crontab -
	@daily  /sbin/shutdown -r +5
	@hourly /bin/bash /home/pi/AutoPai/check-internet.sh
EOF
	echo "--------------------------------------"
	echo "--        Crontabs created          --"
	echo "--------------------------------------"
}

**Comment by chesterlprocter** [comment]
This was just copied from you scripts, but wont be needed unless you'd like it as a tool?

Please confirm and I'll include it.

**Comment by tim0n3** [comment]
Happy to leave it out for now.
Let'ss rather ensure the framework is working on raspbian and ubuntu before adding too many features.
Tx
